Repository hamonikr/hamonize, pull requests merged in 2021-07, with the labels that each got.

#49 add demo server info
  README.md
  hamonize-center/README.md
Labels: documentation

#64 에이전트에서 센터 및 apt저장소 url 수정
  hamonize-agent/etc/hamonize/propertiesJob/propertiesInfo.hm
Labels: enhancement

#66 에이전트 디바이스 정책 오류 수정
  hamonize-agent/src/usb-lockdown/center-lockdown
Labels: bug

#67 센터 정책 배포 결과 오류 수정
  hamonize-agent/src/shell/progrmjob.sh
  hamonize-agent/src/shell/ufwjob.sh
  hamonize-center/src/main/java/com/controller/AuditLogController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentProgramController.java
  hamonize-center/src/main/java/com/controller/curl/CurlUpdtPolicyController.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/ActAgentFirewallController.java
  hamonize-center/src/main/java/com/model/ActAgentProgrmVo.java
  hamonize-center/src/main/resources/publicMapper/auditLogMapper.xml
  hamonize-center/src/main/resources/publicMapper/unauthorizedMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/updateCheckLog_bak.jsp
Labels: bug, enhancement

#69 에이전트 패키징 파일 수정
  hamonize-agent/Makefile
  hamonize-agent/debian/install
  hamonize-agent/debian/postinst
  hamonize-agent/debian/prerm
  hamonize-agent/etc/hamonize/backup/backupInfo.hm
  hamonize-agent/etc/hamonize/firewall/firewallInfo.hm
  hamonize-agent/etc/hamonize/progrm/progrm.hm
  hamonize-agent/etc/hamonize/propertiesJob/propertiesInfo.hm
  hamonize-agent/etc/hamonize/propertiesJob/sgbInitJob.sh
  hamonize-agent/etc/hamonize/recovery/recoveryInfo.hm
  hamonize-agent/etc/hamonize/security/device.hm
  hamonize-agent/etc/hamonize/siteblock/illegalUrls.ini
  hamonize-agent/etc/hamonize/siteblock/siteblock.ini
  hamonize-agent/etc/hamonize/updt/updtInfo.hm
  hamonize-agent/etc/hamonize/uuid
  hamonize-agent/lib/systemd/system/hamonize-agent.service
  hamonize-agent/src/main.js
  hamonize-agent/src/package-lock.json
  hamonize-agent/src/shell/progrmjob.sh
  hamonize-agent/src/shell/tmpprogrmjob.sh
  hamonize-agent/src/usb-lockdown/30-usb-lockdown.rules
  hamonize-agent/src/usb-lockdown/Makefile
  hamonize-agent/src/usb-lockdown/center-lockdown
  hamonize-agent/src/usb-lockdown/usb-lockdown
  hamonize-agent/src/usb-lockdown/usb-lockdown-work
  hamonize-agent/var/log/hamonize/agentjob/.keep
Labels: enhancement

#72 센터 0.5 릴리즈를 위한 기존 버그 수정
  hamonize-center/src/main/java/com/controller/AuditLogController.java
  hamonize-center/src/main/java/com/controller/PolicyDeviceController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentDeviceController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/controller/curl/CurlEqualsHwController.java
  hamonize-center/src/main/java/com/controller/curl/CurlUnAuthorizedController.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/ActAgentFirewallController.java
  hamonize-center/src/main/java/com/mapper/IActAgentDeviceMapper.java
  hamonize-center/src/main/java/com/mapper/IActAgentLogInOutMapper.java
  hamonize-center/src/main/java/com/mapper/IEqualsHwMapper.java
  hamonize-center/src/main/java/com/mapper/IUnauthorizedMapper.java
  hamonize-center/src/main/java/com/model/ActAgentDeviceVo.java
  hamonize-center/src/main/java/com/model/ActAgentFirewallVo.java
  hamonize-center/src/main/java/com/model/AuditLogVo.java
  hamonize-center/src/main/java/com/model/EqualsHwVo.java
  hamonize-center/src/main/java/com/model/LogInOutVo.java
  hamonize-center/src/main/java/com/model/PolicyDeviceVo.java
  hamonize-center/src/main/java/com/service/AuditLogService.java
  hamonize-center/src/main/java/com/service/MntrgService.java
  hamonize-center/src/main/java/com/service/MonitoringService.java
  hamonize-center/src/main/java/com/util/LDAPConnection.java
  hamonize-center/src/main/resources/application.properties
  hamonize-center/src/main/resources/publicMapper/ActAgentDeviceMapper.xml
  hamonize-center/src/main/resources/publicMapper/ActAgentLogInOutMapper.xml
  hamonize-center/src/main/resources/publicMapper/auditLogMapper.xml
  hamonize-center/src/main/resources/publicMapper/equalsHwMapper.xml
  hamonize-center/src/main/resources/publicMapper/hmprogramMapper.xml
  hamonize-center/src/main/resources/publicMapper/pcMangrMapper.xml
  hamonize-center/src/main/resources/publicMapper/unauthorizedMapper.xml
  hamonize-center/src/main/resources/publicMapper/updtPolicyMapper.xml
  hamonize-center/src/main/resources/publicMapper/userMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcChangeLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/prcssBlockLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/updateCheckLog_bak.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView_bak.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu.jsp
Labels: bug, enhancement

#79 센터 백업 관리기능 수정
  hamonize-center/src/main/java/com/controller/BackupController.java
  hamonize-center/src/main/java/com/controller/BackupRecoveryContoller.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentBackupController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentRecoveryController.java
  hamonize-center/src/main/java/com/controller/curl/CurlBackupController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/ActAgentFirewallController.java
  hamonize-center/src/main/java/com/mapper/IBackupMapper.java
  hamonize-center/src/main/java/com/mapper/IGetAgentRecoveryMapper.java
  hamonize-center/src/main/java/com/model/ActAgentBackupRecoveryVo.java
  hamonize-center/src/main/java/com/model/BackupVo.java
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupCycle.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupRecovery.jsp
Labels: enhancement

#82 센터 사용자 정보 페이지 오류 개선
  hamonize-center/src/main/java/com/controller/UserController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/model/UserVo.java
  hamonize-center/src/main/java/com/service/UserService.java
  hamonize-center/src/main/java/com/util/LDAPConnection.java
  hamonize-center/src/main/resources/publicMapper/auditLogMapper.xml
  hamonize-center/src/main/resources/publicMapper/policyDeviceMapper.xml
  hamonize-center/src/main/resources/publicMapper/researchMapper.xml
  hamonize-center/src/main/resources/publicMapper/userMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcChangeLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcInetLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/prcssBlockLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/updateCheckLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupCycle.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupRecovery.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntrngList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/org/orgList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcBlockList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcListMove.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManagePop.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManagePop.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/programManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/screenManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/updtManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/research/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userAdd.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userAdd_unuse.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userList.jsp
Labels: bug

#87 정책관리 > 방화벽,디바이스 등록 에러 수정
  hamonize-center/src/main/java/com/AppConfig.java
  hamonize-center/src/main/java/com/controller/AuditLogController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/model/AuditLogVo.java
  hamonize-center/src/main/java/com/service/MonitoringService.java
  hamonize-center/src/main/resources/publicMapper/auditLogMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcChangeLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcInetLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/prcssBlockLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
Labels: fix

#90 센터 pc 등록 로직 수정
  hamonize-center/db/hamonize_center.sql
  hamonize-center/src/main/java/com/controller/curl/CurlAgentBackupController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentDeviceController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentFirewallController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentNxssController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentProgramController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentUpdtController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController_unuse.java
  hamonize-center/src/main/java/com/controller/curl/CurlEqualsHwController.java
  hamonize-center/src/main/java/com/controller/curl/CurlVersionChkController.java
  hamonize-center/src/main/java/com/controller/curl/ServerCurlController_unuse.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/ActAgentFirewallController.java
  hamonize-center/src/main/java/com/mapper/IEqualsHwMapper.java
  hamonize-center/src/main/java/com/mapper/IOrgMapper.java
  hamonize-center/src/main/java/com/mapper/IPcMangrMapper.java
  hamonize-center/src/main/java/com/service/GroupService.java
  hamonize-center/src/main/java/com/util/LDAPConnection.java
  hamonize-center/src/main/resources/publicMapper/equalsHwMapper.xml
  hamonize-center/src/main/resources/publicMapper/pcMangrMapper.xml
  hamonize-center/src/main/resources/static/js/views/groupManagement.js
  hamonize-center/src/main/resources/static/js/views/notice/notice.js
  hamonize-center/src/main/resources/static/js/views/sgbManagement.js
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/userConectLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupCycle.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/group/groupManagement2.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/org/orgList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/updtManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/research/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userList.jsp
Labels: bug

#92 센터 pc 등록로직 수정
  hamonize-center/db/hamonize_center.sql
  hamonize-center/src/main/java/com/controller/PolicyUpdtController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/mapper/IOrgMapper.java
  hamonize-center/src/main/java/com/mapper/IPcMangrMapper.java
  hamonize-center/src/main/java/com/service/AgentAptListService.java
  hamonize-center/src/main/java/com/service/OrgService.java
  hamonize-center/src/main/java/com/service/UserService.java
  hamonize-center/src/main/resources/publicMapper/orgMapper.xml
  hamonize-center/src/main/resources/publicMapper/pcMangrMapper.xml
  hamonize-center/src/main/resources/publicMapper/policyUpdtMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcChangeLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/prcssBlockLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/updateCheckLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupCycle.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupRecovery.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntrngList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/org/orgList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/programManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/updtManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userAdd.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userList.jsp
Labels: bug, enhancement
