Repository hamonikr/hamonize, pull requests merged in 2021-11, with the labels that each got.

#304 <FIX> : 에이전트서비스 파일 수정
  hamonize-agent/lib/systemd/system/hamonize-agent.service
Labels: fix

#307 <Feat> : add github action - commit msg check
  .github/workflows/check-commit.yml
Labels: good first issue

#328 <Fix> : 메인 모니터링 갯수 오류 수정
  hamonize-center/src/main/java/com/controller/MainController.java
Labels: bug

#334 <Fix> : 모니터링 페이지에서 pc on/off 갯수 오류 수정
  hamonize-center/src/main/java/com/controller/MonitoringController.java
Labels: bug

#348 <Fix> : 부서이동시 백업 안되는 문제 수정
  hamonize-center/src/main/java/com/controller/curl/CurlHamonizeVersionChkController.java
  hamonize-center/src/main/java/com/mapper/IPcMangrMapper.java
  hamonize-center/src/main/java/com/model/RecoveryVo.java
  hamonize-center/src/main/java/com/service/OrgService.java
  hamonize-center/src/main/resources/publicMapper/hamonizeVersionChk.xml
  hamonize-center/src/main/resources/publicMapper/pcMangrMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupRecovery.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
Labels: fix

#356 <Fix>: docker-compose file
  hamonize-center/docker-compose.yml
Labels: bug

#357 <Fix>: apt 패키지 가져오는 로직 수정
  hamonize-center/pom.xml
  hamonize-center/src/main/java/com/service/AgentAptListService.java
  hamonize-center/src/main/resources/logback.xml
Labels: bug

#361 <Fix> : #360 이슈 수정
  hamonize-center/docker-compose.yml
  hamonize-center/ldap-script/gs_backup.ldif
  hamonize-center/ldap-script/start-ldap.sh
  hamonize-center/sql/hamonize_center.sql
Labels: bug, fix

#363 <Fix> : 디바이스 #362
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
Labels: fix

#364 <Fix> : 디바이스 등록시 특수문자 제한 규칙 추가
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
Labels: fix

#366 <Docs> : 테스트 pc 데이터 추가
  hamonize-center/sql/hamonize_center.sql
Labels: documentation

#367 <Docs> : edit sql file
  hamonize-center/sql/hamonize_center.sql
Labels: documentation

#383 <Feat> : 디바이스 차단 제거된 버전
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu2.jsp
  rDeviceRules/debian/changelog
  rDeviceRules/debian/compat
  rDeviceRules/debian/control
  rDeviceRules/debian/install
  rDeviceRules/debian/postinst
  rDeviceRules/debian/postrm
  rDeviceRules/debian/preinst
  rDeviceRules/debian/rules
  rDeviceRules/debian/source/format
  rDeviceRules/etc/udev/rules.d/30-usb-lockdown.rules
Labels: enhancement

#387 #54 add youtube
  README.md
Labels: documentation

#390 <Docs> : 커넥터, 에이전트 동영상 첨부
  README.md
Labels: documentation
