Repository hamonikr/hamonize, pull requests merged in 2021-09, with the labels that each got.

#167 #141 이슈 수정
  LICENSE.md
  README.md
  hamonize-admin/COPYING
  hamonize-admin/NOTICE.md
  hamonize-agent/COPYING
  hamonize-agent/NOTICE.md
  hamonize-center/COPYING
  hamonize-center/NOTICE.md
  hamonize-connector/COPYING
  hamonize-connector/NOTICE.md
Labels: documentation

#168 시큐어 코딩 작업 추가 #160
  hamonize-center/pom.xml
  hamonize-center/src/main/java/com/util/JsonConvertData.java
Labels: bug, dependencies

#165 #128 hamonize-vpn 이미지 버전을 0.2로 업데이트 했습니다.
  hamonize-vpn/docker-compose.yml
Labels: enhancement

#169 #164 서버 관리 페이지 수정
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/resources/application.properties
  hamonize-center/src/main/resources/publicMapper/svrlstMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/admin/view.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/svrlst/list.jsp
Labels: fix

#170 #166 이슈 수정
  hamonize-center/README.md
  img/influx.png
  img/influx1.png
  img/influx2.png
  img/influx3.png
  img/srvlst.png
  img/srvlst2.png
Labels: documentation, enhancement

#183 hamonize-process-mngr 패키지 추가, hamonize-login.service 추가
  hamonize-connector/README.md
  hamonize-connector/src/shell/hamonize-login.service
  hamonize-connector/src/shell/hamonize-process-mngr-1.0.3_amd64.deb
  hamonize-connector/src/shell/hamonizeProgramInstall.sh
  hamonize-connector/src/shell/setServerInfo.sh
  hamonize-connector/src/shell/usb-lockdown/Makefile
Labels: documentation, fix

#186 #173 이슈 처리
  README.md
  hamonize-apt/README.md
  hamonize-apt/apt_build.sh
  hamonize-apt/docker-compose.yml
  hamonize-apt/repo/ssh/authorized_keys
  img/gpg_key.png
Labels: enhancement

#189 에이전트] 복구 수행 이전에 로그아웃 접속로그 전송
  hamonize-agent/src/shell/backupJob_recovery.sh
  hamonize-agent/usr/share/hamonize-agent/shell/backupJob_recovery.sh
Labels: fix

#188 #174 이슈 수정
  README.md
  hamonize-apt/README.md
  hamonize-center/src/main/java/com/service/AuditLogService.java
  hamonize-center/src/main/resources/publicMapper/auditLogMapper.xml
Labels: bug, fix

#191 에이전트 프로그램 버전 확인 수정
  hamonize-agent/src/shell/updtjob.sh
  hamonize-agent/usr/share/hamonize-agent/shell/updtjob.sh
Labels: fix

#195 디바이스 차단 메시지 호환성 수정
  hamonize-connector/debian/control
  hamonize-connector/src/shell/usb-lockdown/usb-lockdown-work
Labels: bug, dependencies

#199 업데이트 정책 수행시 프로그램 버전 체크 명령 수정
  hamonize-agent/src/shell/updtjob.sh
  hamonize-agent/usr/share/hamonize-agent/shell/updtjob.sh
Labels: fix

#200 apt 서버 정보 세팅 수정
  hamonize-connector/src/shell/aptCheck.sh
Labels: fix

#202 커넥터의 의존성 패키지 정리
  hamonize-connector/debian/control
Labels: fix

#204 디바이스 정책 수행 결과 전송 버그 수정
  hamonize-agent/src/main.js
Labels: fix

#207 어드민] ubuntu20.04에서의 hamonize-server 시작 에러 해결
  hamonize-admin/plugins/platform/common/PlatformSessionManager.cpp
  hamonize-admin/plugins/platform/linux/LinuxServiceCore.cpp
  hamonize-admin/plugins/platform/linux/LinuxSessionFunctions.cpp
  hamonize-admin/plugins/platform/linux/LinuxSessionFunctions.h
  hamonize-admin/plugins/vncserver/x11vnc-builtin/BuiltinX11VncServer.cpp
  hamonize-admin/plugins/vncserver/x11vnc-builtin/x11vnc-hamonize.c
  hamonize-admin/postinst
Labels: fix

#211 hamonize-vpn/README.md 의 vpn 연결방법 보충
  hamonize-vpn/README.md
Labels: documentation

#216 조직검색 추가
  hamonize-center/src/main/resources/static/js/ztree/fuzzysearch.js
  hamonize-center/src/main/resources/static/js/ztree/jquery.ztree.exhide.js
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntrngList.jsp
Labels: enhancement

#220 #214
  adminkey/getAdminkey.sh
  adminkey/getAdminkey.sh_aa
  hamonize-center/Dockerfile
  hamonize-center/docker-compose.yml
  hamonize-center/influxdb.conf
  hamonize-center/pom.xml
  hamonize-center/restart.sh
  hamonize-center/server.xml
  hamonize-center/sql/hamonize_center.sql
  hamonize-center/src/main/java/com/controller/AdminController.java
  hamonize-center/src/main/java/com/controller/FileController.java
  hamonize-center/src/main/java/com/controller/MainController.java
  hamonize-center/src/main/java/com/controller/MonitoringController.java
  hamonize-center/src/main/java/com/controller/PcMangrController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentAdminkeyController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentPollingController.java
  hamonize-center/src/main/java/com/controller/curl/CurlController.java
  hamonize-center/src/main/java/com/mapper/IFileMapper.java
  hamonize-center/src/main/java/com/mapper/IScreenManageMapper.java
  hamonize-center/src/main/java/com/mapper/ISvrlstMapper.java
  hamonize-center/src/main/java/com/model/FileVo.java
  hamonize-center/src/main/java/com/model/GetAgentAdminKeyVo.java
  hamonize-center/src/main/java/com/service/NotiService.java
  hamonize-center/src/main/java/com/service/ScreenManageService.java
  hamonize-center/src/main/java/com/util/FileDownload.java
  hamonize-center/src/main/java/com/util/FileUtil.java
  hamonize-center/src/main/resources/application.properties
  hamonize-center/src/main/resources/publicMapper/FileMapper.xml
  hamonize-center/src/main/resources/publicMapper/getAgentPollingMapper.xml
  hamonize-center/src/main/resources/publicMapper/screenManageMapper.xml
  hamonize-center/src/main/resources/publicMapper/svrlstMapper.xml
  hamonize-center/src/main/resources/static/css/sgb/common.css
  hamonize-center/src/main/resources/static/css/sgb/content.css
  hamonize-center/src/main/resources/static/css/sgb/content.css20200205
  hamonize-center/src/main/resources/static/css/sgb/content_bak.css
  hamonize-center/src/main/resources/static/images/key.svg
  hamonize-center/src/main/webapp/WEB-INF/views/admin/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/admin/view.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/login/login.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/main/mainMap.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntrngList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/svrlst/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userAdd.jsp
Labels: enhancement
