Repository hamonikr/hamonize, pull requests merged in 2021-08, with the labels that each got.

#103 센터 소스 정리
  hamonize-center/src/main/java/com/controller/AdminController.java
  hamonize-center/src/main/java/com/controller/BackupController.java
  hamonize-center/src/main/java/com/controller/BackupRecoveryContoller.java
  hamonize-center/src/main/java/com/controller/LoginController.java
  hamonize-center/src/main/java/com/controller/MainController.java
  hamonize-center/src/main/java/com/controller/MonitoringController.java
  hamonize-center/src/main/java/com/controller/NoticeController.java
  hamonize-center/src/main/java/com/controller/OrgController.java
  hamonize-center/src/main/java/com/controller/PcMangrController.java
  hamonize-center/src/main/java/com/controller/PolicyDeviceController.java
  hamonize-center/src/main/java/com/controller/UserController.java
  hamonize-center/src/main/java/com/controller/aptrepository/AgentAptListController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentBackupController.java
  hamonize-center/src/main/java/com/controller/curl/CurlAgentProgramController.java
  hamonize-center/src/main/java/com/controller/curl/CurlEqualsHwController.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/ActAgentFirewallController.java
  hamonize-center/src/main/java/com/controller/curl/agentjob/HashTest.java
  hamonize-center/src/main/java/com/util/LDAPConnection.java
  hamonize-center/src/main/resources/application.properties
  hamonize-center/src/main/resources/publicMapper/userMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUnAuthLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/userConectLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/main/mainMap.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/user/userList.jsp
Labels: enhancement

#105 grafana ip 변경
  hamonize-center/src/main/java/com/HamonizeInterceptor.java
  hamonize-center/src/main/webapp/WEB-INF/views/main/mainMap.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/mntrng/mntmgView.jsp
Labels: enhancement

#110 센터 ui/ux 오류 수정
  hamonize-center/src/main/java/com/controller/PcMangrController.java
  hamonize-center/src/main/resources/publicMapper/pcMangrMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/pcUserLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/prcssBlockLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/auditLog/updateCheckLog.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/login/login.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
Labels: bug

#113 정책 저장시 버튼 더블클릭 안되도록 수정 및 디바이스/방화벽 입력제한 추가
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupCycle.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/backup/backupRecovery.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/org/orgList.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/deviceManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/fireWallManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/programManage.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/policy/updtManage.jsp
Labels: enhancement, good first issue

#114 복구과정에서 불필요 소스 정리
  hamonize-center/src/main/resources/publicMapper/getAgentRecoveryMapper.xml
  hamonize-center/src/main/webapp/WEB-INF/views/pcMngr/pcList.jsp
Labels: enhancement, fix

#121 센터 리드미 수정
  hamonize-center/Dockerfile
  hamonize-center/README.md
  hamonize-center/docker-compose.yml
  hamonize-center/ldap/config/cn=config.ldif
  hamonize-center/ldap/config/cn=config/cn=module{0}.ldif
  hamonize-center/ldap/config/cn=config/cn=schema.ldif
  hamonize-center/ldap/config/cn=config/cn=schema/cn={0}core.ldif
  hamonize-center/ldap/config/cn=config/cn=schema/cn={1}cosine.ldif
  hamonize-center/ldap/config/cn=config/cn=schema/cn={2}inetorgperson.ldif
  hamonize-center/ldap/config/cn=config/cn=schema/cn={3}nis.ldif
  hamonize-center/ldap/config/cn=config/cn=schema/cn={4}ppolicy.ldif
  hamonize-center/ldap/config/docker-openldap-was-started-with-tls
  hamonize-center/sql/hamonize_center.sql
Labels: documentation, enhancement

#132 #115 센터 리드미 수정
  CONTRIBUTING.md
  hamonize-admin/README.md
  hamonize-agent/readme.md
  hamonize-center/README.md
  hamonize-connector/README.md
  img/admin_main.png
  img/center_backup.png
  img/center_device.png
  img/center_hwchg.png
  img/center_login.png
  img/center_main.png
  img/center_monitoring.png
  img/center_monitoring2.png
  img/center_org.png
  img/center_pcmngr1.png
  img/center_pcmngr2.png
  img/center_policy_result.png
  img/center_prcss.png
  img/center_progm.png
  img/center_recov.png
  img/center_ufw.png
  img/center_unauth.png
  img/center_updt.png
  img/center_userlog.png
Labels: documentation, good first issue

#133 openvpn 도커라이징
  hamonize-server/vpn/Dockerfile
  hamonize-server/vpn/openvpn-install.sh
  hamonize-server/vpn/openvpn-set.sh
Labels: enhancement

#134 vpn 서버 도커라이징 리드미 추가
  hamonize-server/vpn/README.md
Labels: documentation

#136 서버관리 기능 추가
  hamonize-center/README.md
  hamonize-center/src/main/java/com/controller/AdminController.java
  hamonize-center/src/main/java/com/controller/LoginController.java
  hamonize-center/src/main/java/com/mapper/ISvrlstMapper.java
  hamonize-center/src/main/java/com/service/SvrlstService.java
  hamonize-center/src/main/resources/publicMapper/adminMapper.xml
  hamonize-center/src/main/resources/publicMapper/svrlstMapper.xml
  hamonize-center/src/main/resources/static/css/sgb/common.css
  hamonize-center/src/main/webapp/WEB-INF/views/admin/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/svrlst/list.jsp
  hamonize-center/src/main/webapp/WEB-INF/views/template/topMenu.jsp
Labels: enhancement

#140 #45 #129 #130 이슈 처리
  hamonize-center/README.md
  hamonize-center/docker-compose.yml
  hamonize-center/env/config.properties
  hamonize-center/grafana.ini
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/CHANGELOG.md
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/LAST_UPDATED
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/MANIFEST.txt
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/README.md
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/GrafanaUtils.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/app.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/Boom.interface.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomOutput.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomPattern.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomSeries.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomSeriesUtils.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomTimeBasedThreshold.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/BoomUtils.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/boom/index.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/app/config.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/css/default.dark.css
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/css/default.light.css
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/module.js
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/partials/editor.html
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/partials/module.html
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/plugin.json
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/azure-monitor-usage.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/debug-ui.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/editor-1.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/editor-2.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/editor-default.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/filters.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/font-awesome-examples.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/img-transform-example.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/influx-usage.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/metrics.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/panel.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/panels-fa.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/prometheus-usage.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/time-based-thresholds.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/src/img/version-5.0.2.png
  hamonize-center/grafana/plugins/yesoreyeram-boomtable-panel/tests/BoomSeries.spec.js
  hamonize-center/hamonize-main.json
  hamonize-center/hamonize-monitoring.json
  hamonize-center/influxdb.conf
  hamonize-center/types.db
  hamonize-server/vpn/README.md
  img/Grafana1.png
  img/Grafana2.png
  img/Grafana3.png
  img/center_servers.png
Labels: documentation, enhancement

#143 #141 이슈 처리 및 센터 리드미 수정
  hamonize-agent/NOTICE.md
  hamonize-center/NOTICE.md
  hamonize-center/README.md
  hamonize-center/docker-compose.yml
  hamonize-center/env/config.properties
  hamonize-connector/NOTICE.md
  hamonize-noti-App/NOTICE.md
  img/center_servers.png
  img/hamonize_center_server.png
Labels: documentation, enhancement, good first issue

#151 어드민 윈도우버전 빌드 설명 추가, 명칭 수정 업데이트
  hamonize-admin/README.md
  hamonize-admin/configurator/src/ServiceConfigurationPage.cpp
  hamonize-admin/core/src/ServiceControl.cpp
  hamonize-admin/master/src/ComputerControlListModel.cpp
  hamonize-admin/translations/veyon_ko.ts
Labels: documentation, fix

#153 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: documentation

#154 edit readme
  README.md
Labels: documentation, enhancement

#156 update cla.yml #7
  .github/workflows/cla.yml
Labels: fix
